import { ChessGame, pieceSets, aiLevels } from './chess.js';
import { puzzles, getPuzzleLabel, getDifficultyLabel } from './puzzles.js';
import { yandex } from './yandex.js';

const LANG_KEY = 'rcq_language';
const i18n = {
  ru: { play:'Играть', puzzles:'Шахматные задачи', howToPlay:'Как играть', settings:'Настройки', back:'Назад', menuSubtitle:'Королевское шахматное приключение', hint:'Подсказка', undo:'Отмена хода', double:'Удвоить награду', nextPuzzle:'Следующая задача', randomPuzzle:'Случайная задача', difficulty:'Сложность', category:'Категория', puzzleNo:'Задача', desc:'Описание', selectLevel:'Выбор сложности бота', novice:'Новичок 😀', amateur:'Любитель 😎', tactician:'Тактик 🧠', master:'Мастер 👑', start:'Начать', coins:'Монеты', holdTimer:'Таймер удержания', shop:'Магазин', boards:'Доски', pieces:'Фигуры', rewarded:'Rewarded video', fullscreen:'Fullscreen ad', level:'Уровень', language:'Язык', all:'Все', gameReady:'Игра началась', puzzleMode:'Режим задач', gameMode:'Игра против бота', statusTurn:'Ход', howTitle:'Правила шахмат', objective:'Цель игры: поставить мат королю соперника.', piecesMove:'Ходы фигур: пешка, конь, слон, ладья, ферзь, король.', check:'Шах: король под атакой и должен защищаться.', mate:'Мат: от шаха нет защиты, партия завершена.', stalemate:'Пат: ходов нет, но шаха нет — ничья.', castling:'Рокировка: король и ладья ходят одновременно при условиях.', promotion:'Превращение пешки: на последней линии пешка становится фигурой.', enPassant:'Взятие на проходе: специальное взятие пешки сразу после двойного хода.', nextRewardDoubled:'Следующая награда будет удвоена', universalHint:'Развивайте фигуры, контролируйте центр и защищайте короля.', nothingToUndo:'Отменять пока нечего', bought:'Куплено', selected:'Выбрано', insufficientCoins:'Недостаточно монет', holdProgress:'До премиального сундука: {minutes} мин', holdClaimed:'Премиальный сундук получен', premiumChestOpened:'Премиальный сундук открыт', premiumChestOpenedReward:'Премиальный сундук открыт: +200 монет' },
  en: { play:'Play', puzzles:'Chess Puzzles', howToPlay:'How to Play', settings:'Settings', back:'Back', menuSubtitle:'Royal chess adventure', hint:'Hint', undo:'Undo', double:'Double reward', nextPuzzle:'Next Puzzle', randomPuzzle:'Random Puzzle', difficulty:'Difficulty', category:'Category', puzzleNo:'Puzzle', desc:'Description', selectLevel:'Choose bot level', novice:'Novice 😀', amateur:'Amateur 😎', tactician:'Tactician 🧠', master:'Master 👑', start:'Start', coins:'Coins', holdTimer:'Retention timer', shop:'Shop', boards:'Boards', pieces:'Pieces', rewarded:'Rewarded video', fullscreen:'Fullscreen ad', level:'Level', language:'Language', all:'All', gameReady:'Game started', puzzleMode:'Puzzle mode', gameMode:'Play vs Bot', statusTurn:'Turn', howTitle:'Chess Rules', objective:'Objective: checkmate the opponent king.', piecesMove:'Piece movement: pawn, knight, bishop, rook, queen, king.', check:'Check: your king is attacked and must respond.', mate:'Checkmate: no legal defense from check, game over.', stalemate:'Stalemate: no legal moves, no check — draw.', castling:'Castling: king and rook move together if conditions are met.', promotion:'Pawn promotion: pawn promotes on the last rank.', enPassant:'En passant: special pawn capture right after a two-square move.', nextRewardDoubled:'The next reward will be doubled', universalHint:'Develop your pieces, control the center, and keep your king safe.', nothingToUndo:'Nothing to undo yet', bought:'Owned', selected:'Selected', insufficientCoins:'Not enough coins', holdProgress:'To premium chest: {minutes} min', holdClaimed:'Premium chest claimed', premiumChestOpened:'Premium chest opened', premiumChestOpenedReward:'Premium chest opened: +200 coins' },
  tr: { play:'Oyna', puzzles:'Satranç Bulmacaları', howToPlay:'Nasıl Oynanır', settings:'Ayarlar', back:'Geri', menuSubtitle:'Kraliyet satranç macerası', hint:'İpucu', undo:'Geri al', double:'Ödülü ikiye katla', nextPuzzle:'Sonraki Bulmaca', randomPuzzle:'Rastgele Bulmaca', difficulty:'Zorluk', category:'Kategori', puzzleNo:'Bulmaca', desc:'Açıklama', selectLevel:'Bot seviyesi seç', novice:'Acemi 😀', amateur:'Amatör 😎', tactician:'Taktikçi 🧠', master:'Usta 👑', start:'Başlat', coins:'Paralar', holdTimer:'Tutma sayacı', shop:'Mağaza', boards:'Tahtalar', pieces:'Taşlar', rewarded:'Rewarded video', fullscreen:'Tam ekran reklam', level:'Seviye', language:'Dil', all:'Tümü', gameReady:'Oyun başladı', puzzleMode:'Bulmaca modu', gameMode:'Bot ile Oyun', statusTurn:'Sıra', howTitle:'Satranç Kuralları', objective:'Amaç: rakip şahı mat etmek.', piecesMove:'Taş hareketleri: piyon, at, fil, kale, vezir, şah.', check:'Şah: şah tehdit altında ve yanıt vermeli.', mate:'Mat: şahtan kaçış yok, oyun biter.', stalemate:'Pat: yasal hamle yok, şah yok — beraberlik.', castling:'Rok: şah ve kale uygun koşullarda birlikte hareket eder.', promotion:'Piyon terfisi: piyon son sırada taşa dönüşür.', enPassant:'Geçerken alma: çift adım sonrası özel piyon alışı.', nextRewardDoubled:'Bir sonraki ödül ikiye katlanacak', universalHint:'Taşlarınızı geliştirin, merkezi kontrol edin ve şahınızı koruyun.', nothingToUndo:'Henüz geri alınacak hamle yok', bought:'Satın alındı', selected:'Seçili', insufficientCoins:'Yetersiz para', holdProgress:'Premium sandığa kalan: {minutes} dk', holdClaimed:'Premium sandık alındı', premiumChestOpened:'Premium sandık açıldı', premiumChestOpenedReward:'Premium sandık açıldı: +200 para' }
};

const t = (k, vars={}) => { const text=i18n[state.language]?.[k] || i18n.ru[k] || k; return text.replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? `{${name}}`); };
const stateDefaults = { coins:120, completedPuzzles:[], language:'ru', aiLevel:'amateur', puzzleDifficulty:'all', lastPuzzleId:null, holdMs:600000, sessionSeconds:0, retentionRewardClaimed:false, activeBoardTheme:'royal', ownedBoardThemes:['royal'], activePieceSet:'classic', ownedPieceSets:['classic'] };
const SHOP_ITEMS = {
  boards: [
    { id:'royal', name:'Royal Gold', price:0 },
    { id:'neon', name:'Neon Cyber', price:240 },
    { id:'glass', name:'Frozen Glass', price:420 }
  ],
  pieces: [
    { id:'classic', name:'Classic Unicode', price:0 },
    { id:'glyph', name:'Runic Glyphs', price:180 },
    { id:'minimal', name:'Minimal Dots', price:300 }
  ]
};
const game = new ChessGame();
let state = { ...stateDefaults, language: localStorage.getItem(LANG_KEY) || 'ru' };
let screen='menu', mode='ai', activePuzzle=null, selected=null, legalTargets=[], holdTick=null, rewardMultiplierArmed=false, lastSaveTs=0;
const app=document.querySelector('#app'); const toastEl=document.querySelector('#toast');

(async()=>{await yandex.init();state={...stateDefaults,...migrateState(await yandex.load(stateDefaults)),language:localStorage.getItem(LANG_KEY)||'ru'};render();app.addEventListener('click',onClick);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveState(true);});window.addEventListener('beforeunload',()=>saveState(true));})();

function onClick(e){const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;
if(a==='go-menu'){screen='menu';render();}
if(a==='go-game'){screen='difficulty';render();}
if(a==='go-puzzles'){mode='puzzle';screen='game';pickPuzzle(false);render();}
if(a==='go-how'){screen='how';render();}
if(a==='go-settings'){screen='settings';render();}
if(a==='start-ai'){mode='ai';game.reset('start');screen='game';showToast(t('gameReady'));render();}
if(a==='set-ai'){state.aiLevel=e.target.dataset.level;saveState();render();}
if(a==='set-filter'){state.puzzleDifficulty=e.target.value;saveState();pickPuzzle(false);render();}
if(a==='next-puzzle'){pickPuzzle(false);render();}
if(a==='rand-puzzle'){pickPuzzle(true);render();}
if(a==='hint'){showToast(mode==='puzzle'?(activePuzzle?.hint?.[state.language]||''):t('universalHint'));}
if(a==='undo'){
const firstUndo=game.undo?.();
if(mode==='ai'&&firstUndo){game.undo?.();}
if(firstUndo){render();}else{showToast(t('nothingToUndo'));}
}
if(a==='double'){rewardMultiplierArmed=true;showToast(t('nextRewardDoubled'));}
if(a==='lang'){state.language=e.target.dataset.lang;localStorage.setItem(LANG_KEY,state.language);saveState();render();}
if(a==='shop-board')handleShopSelection('boards',e.target.dataset.item);
if(a==='shop-piece')handleShopSelection('pieces',e.target.dataset.item);
}

function render(){stopTimer();if(screen==='menu')return renderMenu();if(screen==='difficulty')return renderDifficulty();if(screen==='how')return renderHow();if(screen==='settings')return renderSettings();return renderGame();}
function renderMenu(){app.innerHTML=`<section class='menu-screen'><div class='menu-card'><h1>Royal Chess Quest</h1><p>${t('menuSubtitle')}</p><div class='menu-actions'><button class='btn btn-menu' data-action='go-game'>${t('play')}</button><button class='btn btn-menu' data-action='go-puzzles'>${t('puzzles')}</button><button class='btn btn-menu' data-action='go-how'>${t('howToPlay')}</button><button class='btn btn-menu' data-action='go-settings'>${t('settings')}</button></div></div></section>`;}
function renderDifficulty(){app.innerHTML=`<section class='simple-screen'><button class='btn btn-soft back' data-action='go-menu'>← ${t('back')}</button><div class='glass-card'><h2>${t('selectLevel')}</h2>${Object.keys(aiLevels).map(k=>`<button class='btn btn-soft ${state.aiLevel===k?'active-lang':''}' data-action='set-ai' data-level='${k}'>${t(k)}</button>`).join('')}<button class='btn btn-gold full-width' data-action='start-ai'>${t('start')}</button></div></section>`;}
function renderHow(){app.innerHTML=`<section class='simple-screen'><button class='btn btn-soft back' data-action='go-menu'>← ${t('back')}</button><div class='glass-card rules'><h2>${t('howTitle')}</h2><ul><li>${t('objective')}</li><li>${t('piecesMove')}</li><li>${t('check')}</li><li>${t('mate')}</li><li>${t('stalemate')}</li><li>${t('castling')}</li><li>${t('promotion')}</li><li>${t('enPassant')}</li></ul></div></section>`;}
function renderSettings(){app.innerHTML=`<section class='simple-screen'><button class='btn btn-soft back' data-action='go-menu'>← ${t('back')}</button><div class='glass-card'><h2>${t('settings')}</h2><p>${t('language')}</p><div class='lang-row'><button class='btn btn-soft ${state.language==='ru'?'active-lang':''}' data-action='lang' data-lang='ru'>Русский</button><button class='btn btn-soft ${state.language==='en'?'active-lang':''}' data-action='lang' data-lang='en'>English</button><button class='btn btn-soft ${state.language==='tr'?'active-lang':''}' data-action='lang' data-lang='tr'>Türkçe</button></div></div></section>`;}
function renderGame(){document.documentElement.dataset.boardTheme=state.activeBoardTheme;app.innerHTML=`<header class='topbar'><button class='btn btn-soft' data-action='go-menu'>← ${t('back')}</button><div class='wallet'>🪙 ${t('coins')}: <strong>${state.coins}</strong></div></header><main class='layout'><section class='board-card'>${mode==='puzzle'?puzzleHeader():''}<div id='board' class='chess-board'></div><div class='status-panel'><p id='status'></p><div class='action-row'><button class='btn btn-soft' data-action='hint'>${t('hint')}</button><button class='btn btn-soft' data-action='undo'>${t('undo')}</button><button class='btn btn-gold' data-action='double'>${t('double')}</button></div></div></section><aside class='side-panel'><div class='glass-card'><h3>${t('holdTimer')}</h3><p id='hold-timer'>10:00</p><p id='hold-progress'></p></div><div class='glass-card'><h3>${t('shop')}</h3>${renderShopSection('boards','shop-board')}${renderShopSection('pieces','shop-piece')}</div><div class='glass-card'><h3>${t('rewarded')}</h3><p>Placeholder</p></div><div class='glass-card'><h3>${t('fullscreen')}</h3><p>Placeholder</p></div></aside></main>`;renderBoard();updateHoldUi();startTimer();}
function puzzleHeader(){return `<div class='glass-card puzzle-top'><h3>${activePuzzle.title[state.language]}</h3><p><b>${t('puzzleNo')}:</b> ${activePuzzle.id} · <b>${t('category')}:</b> ${getPuzzleLabel(activePuzzle.category,state.language)} · <b>${t('difficulty')}:</b> ${getDifficultyLabel(activePuzzle.difficulty,state.language)}</p><p><b>${t('desc')}:</b> ${activePuzzle.description[state.language]}</p><p><b>${t('hint')}:</b> ${activePuzzle.hint[state.language]}</p><div class='action-row'><select class='btn btn-soft' data-action='set-filter'><option value='all' ${state.puzzleDifficulty==='all'?'selected':''}>${getDifficultyLabel('all',state.language)}</option><option value='easy' ${state.puzzleDifficulty==='easy'?'selected':''}>${getDifficultyLabel('easy',state.language)}</option><option value='medium' ${state.puzzleDifficulty==='medium'?'selected':''}>${getDifficultyLabel('medium',state.language)}</option><option value='hard' ${state.puzzleDifficulty==='hard'?'selected':''}>${getDifficultyLabel('hard',state.language)}</option><option value='expert' ${state.puzzleDifficulty==='expert'?'selected':''}>${getDifficultyLabel('expert',state.language)}</option></select><button class='btn btn-soft' data-action='next-puzzle'>${t('nextPuzzle')}</button><button class='btn btn-soft' data-action='rand-puzzle'>${t('randomPuzzle')}</button></div></div>`;}
function renderBoard(){const b=document.querySelector('#board'); if(!b) return; const set=pieceSets[state.activePieceSet]||pieceSets.classic; b.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=document.createElement('button');sq.className=`square ${(r+c)%2?'dark':'light'}`;const p=game.getPiece(r,c);if(p){sq.textContent=p.color==='w'?set.white[p.type]:set.black[p.type];sq.classList.add('piece');} if(selected&&selected.row===r&&selected.col===c)sq.classList.add('selected'); if(legalTargets.some(t=>t.row===r&&t.col===c))sq.classList.add('legal-target');sq.onclick=()=>onSquare(r,c);b.appendChild(sq);}document.querySelector('#status').textContent=`${t('statusTurn')}: ${game.turn}`;}
function renderShopSection(type,action){return `<h4>${t(type)}</h4><div class='shop-list'>${SHOP_ITEMS[type].map(item=>{const owned=(type==='boards'?state.ownedBoardThemes:state.ownedPieceSets).includes(item.id);const active=type==='boards'?state.activeBoardTheme===item.id:state.activePieceSet===item.id;const badge=active?t('selected'):(owned?t('bought'):`🪙 ${item.price}`);return `<button class='btn btn-soft full-width' data-action='${action}' data-item='${item.id}'><strong>${item.name}</strong><br><span>${badge}</span></button>`;}).join('')}</div>`;}
function handleShopSelection(type,id){const items=SHOP_ITEMS[type];const item=items.find(x=>x.id===id);if(!item)return;const ownedKey=type==='boards'?'ownedBoardThemes':'ownedPieceSets';const activeKey=type==='boards'?'activeBoardTheme':'activePieceSet';const owned=state[ownedKey];if(owned.includes(id)){state[activeKey]=id;saveState();render();return;}if(state.coins<item.price){showToast(t('insufficientCoins'));return;}state.coins-=item.price;state[ownedKey]=[...owned,id];state[activeKey]=id;saveState();render();}
function migrateState(loaded){const next={...loaded};if(!Array.isArray(next.ownedBoardThemes)||!next.ownedBoardThemes.length)next.ownedBoardThemes=['royal'];if(!Array.isArray(next.ownedPieceSets)||!next.ownedPieceSets.length)next.ownedPieceSets=['classic'];if(!next.ownedBoardThemes.includes('royal'))next.ownedBoardThemes.unshift('royal');if(!next.ownedPieceSets.includes('classic'))next.ownedPieceSets.unshift('classic');if(!next.activeBoardTheme)next.activeBoardTheme='royal';if(!next.activePieceSet)next.activePieceSet='classic';if(typeof next.sessionSeconds!=='number'||Number.isNaN(next.sessionSeconds)){const oldHoldMs=typeof next.holdMs==='number'?next.holdMs:600000;next.sessionSeconds=Math.max(0,Math.floor((600000-oldHoldMs)/1000));}next.sessionSeconds=Math.max(0,Math.floor(next.sessionSeconds));if(typeof next.retentionRewardClaimed!=='boolean')next.retentionRewardClaimed=false;return next;}
function onSquare(row,col){const piece=game.getPiece(row,col);if(selected){const move=game.makeMove(selected,{row,col});if(move){selected=null;legalTargets=[];afterMove(move);renderBoard();return;}}if(piece&&piece.color===game.turn){selected={row,col};legalTargets=game.legalMoves().filter(m=>m.from.row===row&&m.from.col===col).map(m=>m.to);}else{selected=null;legalTargets=[];}renderBoard();}
function afterMove(move){const notation=game.moveToNotation(move);if(mode==='puzzle'){if(notation===activePuzzle.solution){if(!state.completedPuzzles.includes(activePuzzle.id))state.completedPuzzles.push(activePuzzle.id);const reward=rewardMultiplierArmed?activePuzzle.reward*2:activePuzzle.reward;state.coins+=reward;rewardMultiplierArmed=false;saveState();showToast(`+${reward}`);pickPuzzle(false);render();}return;}if(!game.status().over){setTimeout(()=>{const aiMove=game.bestMove('b',aiLevels[state.aiLevel]||aiLevels.amateur);if(aiMove) game.applyMove(aiMove,'q',true);renderBoard();},300);}}
function pickPuzzle(randomAny){const filt=state.puzzleDifficulty==='all'?puzzles:puzzles.filter(p=>p.difficulty===state.puzzleDifficulty);let unresolved=filt.filter(p=>!state.completedPuzzles.includes(p.id));let pool=(randomAny?filt:(unresolved.length?unresolved:filt)).filter(p=>p.id!==state.lastPuzzleId);if(!pool.length) pool=filt;activePuzzle=pool[Math.floor(Math.random()*pool.length)];state.lastPuzzleId=activePuzzle.id;game.reset(activePuzzle.fen);}
function startTimer(){holdTick=setInterval(()=>{state.sessionSeconds+=1;updateHoldUi();checkRetentionReward();saveState();},1000);}

function updateHoldUi(){const elapsed=Math.max(0,Math.floor(state.sessionSeconds));const clamped=Math.min(elapsed,600);const remaining=Math.max(0,600-clamped);const mm=String(Math.floor(clamped/60)).padStart(2,'0');const ss=String(clamped%60).padStart(2,'0');const timerEl=document.querySelector('#hold-timer');if(timerEl)timerEl.textContent=`${mm}:${ss}`;const progressEl=document.querySelector('#hold-progress');if(!progressEl)return;if(state.retentionRewardClaimed){progressEl.textContent=t('holdClaimed');return;}const remainingMinutes=Math.ceil(remaining/60);progressEl.textContent=t('holdProgress',{minutes:remainingMinutes});}

function checkRetentionReward(){if(state.retentionRewardClaimed||state.sessionSeconds<600)return;state.coins+=200;state.retentionRewardClaimed=true;showToast(t('premiumChestOpenedReward'));saveState(true);}
function stopTimer(){if(holdTick){clearInterval(holdTick);holdTick=null;}}
function saveState(force=false){const now=Date.now();if(!force&&now-lastSaveTs<15000)return;lastSaveTs=now;yandex.save(state);} function showToast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1200);} 
