const tr = {
  categories: {
    mate1: { ru: 'Мат в 1 ход', en: 'Mate in 1', tr: '1 Hamlede Mat' },
    mate2: { ru: 'Мат в 2 хода', en: 'Mate in 2', tr: '2 Hamlede Mat' },
    fork: { ru: 'Вилка', en: 'Fork', tr: 'Çatal' },
    pin: { ru: 'Связка', en: 'Pin', tr: 'Açmaz' },
    discovered: { ru: 'Вскрытое нападение', en: 'Discovered Attack', tr: 'Açık Saldırı' },
    defense: { ru: 'Защита', en: 'Defense', tr: 'Savunma' },
    endgame: { ru: 'Эндшпиль', en: 'Endgame', tr: 'Oyunsonu' },
    promotion: { ru: 'Превращение пешки', en: 'Promotion', tr: 'Terfi' },
    tactical: { ru: 'Тактика', en: 'Tactics', tr: 'Taktik' },
    winQueen: { ru: 'Выигрыш ферзя', en: 'Win the Queen', tr: 'Veziri Kazan' }
  },
  difficulty: {
    all: { ru: 'Все', en: 'All', tr: 'Tümü' },
    easy: { ru: 'Легко', en: 'Easy', tr: 'Kolay' },
    medium: { ru: 'Средне', en: 'Medium', tr: 'Orta' },
    hard: { ru: 'Сложно', en: 'Hard', tr: 'Zor' },
    expert: { ru: 'Эксперт', en: 'Expert', tr: 'Uzman' }
  }
};

export function getPuzzleLabel(type, lang='ru') { return tr.categories[type]?.[lang] || type; }
export function getDifficultyLabel(level, lang='ru') { return tr.difficulty[level]?.[lang] || level; }

const hint = {
  mate: { ru: 'Ищите форсирующий шах.', en: 'Look for a forcing check.', tr: 'Zorlayıcı şahı ara.' },
  tactic: { ru: 'Считайте взятия до конца.', en: 'Calculate captures to the end.', tr: 'Alışları sonuna kadar hesapla.' },
  defense: { ru: 'Устраните главную угрозу.', en: 'Neutralize the main threat.', tr: 'Ana tehdidi etkisizleştir.' }
};

export const puzzles = [
  { id: 1, title: { ru: 'Мат слоном', en: 'Bishop Mate', tr: 'Fil Matı' }, description: { ru: 'Мат в 1 ход.', en: 'Mate in 1.', tr: '1 hamlede mat.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/4BPPP/6K1 w - - 0 1', solution: 'e2a6', hint: hint.mate, reward: 34 },
  { id: 2, title: { ru: 'Ладейный финал', en: 'Rook Finish', tr: 'Kale Bitişi' }, description: { ru: 'Мат в 1 ход.', en: 'Mate in 1.', tr: '1 hamlede mat.' }, category: 'mate1', difficulty: 'easy', fen: '7k/6pp/8/8/8/8/5PPP/R5K1 w - - 0 1', solution: 'a1a8', hint: hint.mate, reward: 35 },
  { id: 3, title: { ru: 'Ферзь по диагонали', en: 'Diagonal Queen Mate', tr: 'Çapraz Vezir Matı' }, description: { ru: 'Точный матующий ход.', en: 'Find the exact mating move.', tr: 'Kesin mat hamlesini bul.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5pp1/6qp/8/8/3Q4/5PPP/6K1 w - - 0 1', solution: 'd3d8', hint: hint.mate, reward: 36 },
  { id: 4, title: { ru: 'Мат конём', en: 'Knight Mate', tr: 'At Matı' }, description: { ru: 'Неожиданный мат в 1.', en: 'Unexpected mate in 1.', tr: 'Beklenmedik 1 hamlede mat.' }, category: 'mate1', difficulty: 'medium', fen: '6k1/5ppp/8/8/8/3N4/5PPP/6K1 w - - 0 1', solution: 'd3e5', hint: hint.mate, reward: 48 },
  { id: 5, title: { ru: 'Мат с h-линии', en: 'H-file Mate', tr: 'H Dikeyi Matı' }, description: { ru: 'Один точный шах.', en: 'One precise check.', tr: 'Tek doğru şah.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/5PPQ/6K1 w - - 0 1', solution: 'h2h8', hint: hint.mate, reward: 33 },
  { id: 6, title: { ru: 'Король в сети', en: 'King in Net', tr: 'Ağdaki Şah' }, description: { ru: 'Мат на ограниченном поле.', en: 'Mate in a restricted box.', tr: 'Kısıtlı alanda mat.' }, category: 'mate1', difficulty: 'medium', fen: '5rk1/6pp/8/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 50 },
  { id: 7, title: { ru: 'Мат ферзём по ряду', en: 'Rank Queen Mate', tr: 'Yatay Vezir Matı' }, description: { ru: 'Мат последним рядом.', en: 'Mate on the back rank.', tr: 'Arka sırada mat.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/6pp/8/8/8/8/4QPPP/6K1 w - - 0 1', solution: 'e2e8', hint: hint.mate, reward: 32 },
  { id: 8, title: { ru: 'Тихий мат', en: 'Quiet Mate', tr: 'Sessiz Mat' }, description: { ru: 'Сначала занять поле, потом угроза неотразима.', en: 'Occupy the key square with mate.', tr: 'Kilit kareyi al ve mat et.' }, category: 'mate1', difficulty: 'medium', fen: '7k/5pp1/8/6Q1/8/8/5PPP/6K1 w - - 0 1', solution: 'g5d8', hint: hint.mate, reward: 47 },

  { id: 9, title: { ru: 'Подготовка мата', en: 'Mate Setup', tr: 'Mat Hazırlığı' }, description: { ru: 'Начните мат в 2 хода.', en: 'Start a mate in 2 sequence.', tr: '2 hamlede mat dizisini başlat.' }, category: 'mate2', difficulty: 'medium', fen: '6k1/5ppp/8/8/8/3Q4/5PPP/6K1 w - - 0 1', solution: 'd3d8', hint: hint.mate, reward: 52 },
  { id: 10, title: { ru: 'Отвлечение защитника', en: 'Deflect Defender', tr: 'Savunucuyu Saptır' }, description: { ru: 'Уберите ключевую фигуру.', en: 'Deflect the key defender.', tr: 'Kilit savunucuyu saptır.' }, category: 'mate2', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.mate, reward: 77 },
  { id: 11, title: { ru: 'Мат по диагонали за 2', en: 'Diagonal Mate in 2', tr: '2 Hamlede Çapraz Mat' }, description: { ru: 'Найдите первый форсирующий ход.', en: 'Find the first forcing move.', tr: 'İlk zorlayıcı hamleyi bul.' }, category: 'mate2', difficulty: 'hard', fen: '6k1/4bppp/8/8/8/2Q5/5PPP/6K1 w - - 0 1', solution: 'c3c8', hint: hint.mate, reward: 75 },
  { id: 12, title: { ru: 'Жертва ради сети', en: 'Sacrifice for Net', tr: 'Ağ İçin Feda' }, description: { ru: 'Создайте матовую сеть.', en: 'Build a mating net.', tr: 'Mat ağı kur.' }, category: 'mate2', difficulty: 'expert', fen: '6k1/5ppp/8/8/8/5Q2/6PP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 104 },
  { id: 13, title: { ru: 'Перевод ферзя', en: 'Queen Transfer', tr: 'Vezir Transferi' }, description: { ru: 'Точный перевод в атаку.', en: 'Precise transfer into attack.', tr: 'Saldırıya kesin transfer.' }, category: 'mate2', difficulty: 'medium', fen: '7k/5ppp/8/8/8/6Q1/5PPP/6K1 w - - 0 1', solution: 'g3b8', hint: hint.mate, reward: 55 },
  { id: 14, title: { ru: 'Подрезать короля', en: 'Cut Off King', tr: 'Şahı Kes' }, description: { ru: 'Ход ладьёй запускает форсированный мат.', en: 'Rook move starts forced mate.', tr: 'Kale hamlesi zorunlu matı başlatır.' }, category: 'mate2', difficulty: 'hard', fen: '6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1', solution: 'd1d8', hint: hint.mate, reward: 71 },

  { id: 15, title: { ru: 'Классическая вилка', en: 'Classic Fork', tr: 'Klasik Çatal' }, description: { ru: 'Конь бьёт две цели.', en: 'Knight attacks two targets.', tr: 'At iki hedefe saldırır.' }, category: 'fork', difficulty: 'easy', fen: '4k3/8/8/3q4/8/4N3/8/4K3 w - - 0 1', solution: 'e3d5', hint: hint.tactic, reward: 38 },
  { id: 16, title: { ru: 'Вилка в центре', en: 'Central Fork', tr: 'Merkez Çatalı' }, description: { ru: 'Прыжок коня выигрывает материал.', en: 'Knight jump wins material.', tr: 'At sıçrayışı taş kazanır.' }, category: 'fork', difficulty: 'medium', fen: 'r2q1rk1/ppp2ppp/2n5/8/3P4/2N2N2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 54 },
  { id: 17, title: { ru: 'Скачок на c6', en: 'Jump to c6', tr: 'c6 Sıçrayışı' }, description: { ru: 'Тактическая вилка с темпом.', en: 'Tactical fork with tempo.', tr: 'Tempolu taktik çatal.' }, category: 'fork', difficulty: 'medium', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/5N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 56 },
  { id: 18, title: { ru: 'Коневой укол', en: 'Knight Jab', tr: 'At İğnesi' }, description: { ru: 'Точный форк у короля.', en: 'Precise fork near king.', tr: 'Şah yanında kesin çatal.' }, category: 'fork', difficulty: 'hard', fen: 'r1bq1rk1/ppp2ppp/2n5/3n4/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3e4', hint: hint.tactic, reward: 72 },
  { id: 19, title: { ru: 'Вилка пешкой', en: 'Pawn Fork', tr: 'Piyon Çatalı' }, description: { ru: 'Пешка тоже может вилковать.', en: 'Pawn can fork too.', tr: 'Piyon da çatal yapar.' }, category: 'fork', difficulty: 'easy', fen: '4k3/8/8/3r4/4p3/3P4/8/4K3 w - - 0 1', solution: 'd3e4', hint: hint.tactic, reward: 37 },
  { id: 20, title: { ru: 'Вилка в эндшпиле', en: 'Endgame Fork', tr: 'Oyunsonu Çatalı' }, description: { ru: 'Выиграйте качество коневым ударом.', en: 'Win exchange by knight fork.', tr: 'At çatalıyla kalite kazan.' }, category: 'fork', difficulty: 'hard', fen: '5k2/8/3r4/8/3N4/8/8/4K3 w - - 0 1', solution: 'd4e6', hint: hint.tactic, reward: 80 },
  { id: 21, title: { ru: 'Форк на f7', en: 'Fork on f7', tr: 'f7 Çatalı' }, description: { ru: 'Типовой тактический мотив.', en: 'Typical tactical motif.', tr: 'Tipik taktik motif.' }, category: 'fork', difficulty: 'medium', fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/3NP3/5N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4f5', hint: hint.tactic, reward: 58 },

  { id: 22, title: { ru: 'Связка по вертикали', en: 'Vertical Pin', tr: 'Dikey Açmaz' }, description: { ru: 'Свяжите фигуру на линии.', en: 'Pin a piece on the file.', tr: 'Dikeyde taşı açmaza al.' }, category: 'pin', difficulty: 'medium', fen: '2r3k1/5ppp/3q4/8/3Q4/8/5PPP/6K1 w - - 0 1', solution: 'd4d6', hint: hint.tactic, reward: 50 },
  { id: 23, title: { ru: 'Диагональная связка', en: 'Diagonal Pin', tr: 'Çapraz Açmaz' }, description: { ru: 'Сковать защитника короля.', en: 'Pin the king defender.', tr: 'Şah savunucusunu bağla.' }, category: 'pin', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.tactic, reward: 74 },
  { id: 24, title: { ru: 'Ладья давит', en: 'Rook Pressure Pin', tr: 'Kale Baskı Açmazı' }, description: { ru: 'Связка по 8-й линии.', en: 'Pin on the 8th rank.', tr: '8. yatayda açmaz.' }, category: 'pin', difficulty: 'medium', fen: '5rk1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1', solution: 'd1d8', hint: hint.tactic, reward: 49 },
  { id: 25, title: { ru: 'Точная связка слоном', en: 'Bishop Pin', tr: 'Fil Açmazı' }, description: { ru: 'Слон фиксирует фигуру.', en: 'Bishop pins the piece.', tr: 'Fil taşı açmaza alır.' }, category: 'pin', difficulty: 'easy', fen: 'r3k2r/ppp2ppp/2n5/8/3P4/2P2B2/PP3PPP/R3K2R w KQkq - 0 1', solution: 'f3c6', hint: hint.tactic, reward: 40 },
  { id: 26, title: { ru: 'Связка и выигрыш', en: 'Pin and Win', tr: 'Açmaz ve Kazanç' }, description: { ru: 'Используйте связанность для взятия.', en: 'Exploit the pin to win material.', tr: 'Açmazı taş kazanmak için kullan.' }, category: 'pin', difficulty: 'hard', fen: 'r1b2rk1/ppp2ppp/2n5/3q4/3P4/2N2Q2/PP3PPP/R1B2RK1 w - - 0 1', solution: 'f3d5', hint: hint.tactic, reward: 79 },
  { id: 27, title: { ru: 'Защитная связка', en: 'Defensive Pin', tr: 'Savunma Açmazı' }, description: { ru: 'Связка как ресурс обороны.', en: 'Pin as a defensive resource.', tr: 'Savunmada açmaz kaynağı.' }, category: 'pin', difficulty: 'expert', fen: '3r2k1/5ppp/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.defense, reward: 102 },

  { id: 28, title: { ru: 'Вскрытый нажим', en: 'Discovered Pressure', tr: 'Açık Baskı' }, description: { ru: 'Откройте атаку центральным толчком.', en: 'Open attack with a central push.', tr: 'Merkez sürüşüyle saldırıyı aç.' }, category: 'discovered', difficulty: 'medium', fen: 'r3k2r/ppp2ppp/2n5/3qp3/3P4/2P2N2/PP3PPP/R1BQ1RK1 w kq - 0 1', solution: 'd4e5', hint: hint.tactic, reward: 57 },
  { id: 29, title: { ru: 'Вскрытый шах', en: 'Discovered Check', tr: 'Açık Şah' }, description: { ru: 'Освободите линию шаха.', en: 'Open line for discovered check.', tr: 'Açık şah için hattı aç.' }, category: 'discovered', difficulty: 'hard', fen: 'r1bqk2r/pppp1ppp/4pn2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 82 },
  { id: 30, title: { ru: 'Вскрытая атака конём', en: 'Knight Discovered Attack', tr: 'Atla Açık Saldırı' }, description: { ru: 'Отведите коня и откройте линию.', en: 'Move the knight and open the line.', tr: 'Atı çek ve hattı aç.' }, category: 'discovered', difficulty: 'hard', fen: 'r2q1rk1/ppp2ppp/2n5/8/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'f3e5', hint: hint.tactic, reward: 76 },
  { id: 31, title: { ru: 'Вскрытый удар слоном', en: 'Bishop Discovery', tr: 'Fille Açık Vuruş' }, description: { ru: 'Откройте диагональ для слона.', en: 'Open diagonal for bishop.', tr: 'Fil için çaprazı aç.' }, category: 'discovered', difficulty: 'medium', fen: 'r1bq1rk1/ppp2ppp/2n5/8/3P4/2PBBN2/PP3PPP/R2Q1RK1 w - - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 53 },
  { id: 32, title: { ru: 'Двойной выстрел', en: 'Double Shot Discovery', tr: 'Çifte Açık Vuruş' }, description: { ru: 'Вскрытие с двойной угрозой.', en: 'Discovery with a double threat.', tr: 'Çifte tehditli açık saldırı.' }, category: 'discovered', difficulty: 'expert', fen: 'r1bqk2r/ppp2ppp/2n1pn2/8/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w kq - 0 1', solution: 'c2h7', hint: hint.tactic, reward: 110 },

  { id: 33, title: { ru: 'Единственный ход', en: 'Only Move', tr: 'Tek Hamle' }, description: { ru: 'Защититесь от немедленной угрозы.', en: 'Defend against immediate threat.', tr: 'Anlık tehdide karşı savun.' }, category: 'defense', difficulty: 'easy', fen: '4k3/8/8/8/8/8/5q2/4K2R w - - 0 1', solution: 'e1f2', hint: hint.defense, reward: 33 },
  { id: 34, title: { ru: 'Размен для спасения', en: 'Trade to Survive', tr: 'Hayatta Kalmak İçin Değişim' }, description: { ru: 'Упростите позицию.', en: 'Simplify the position.', tr: 'Pozisyonu sadeleştir.' }, category: 'defense', difficulty: 'medium', fen: '4r1k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1', solution: 'd1e1', hint: hint.defense, reward: 48 },
  { id: 35, title: { ru: 'Покрыть матовое поле', en: 'Cover Mate Square', tr: 'Mat Karesini Kapat' }, description: { ru: 'Точный защитный ход пешкой.', en: 'Precise pawn defensive move.', tr: 'Kesin piyon savunması.' }, category: 'defense', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/4Q1PP/6K1 w - - 0 1', solution: 'g2g3', hint: hint.defense, reward: 36 },
  { id: 36, title: { ru: 'Контрудар в защите', en: 'Counterblow Defense', tr: 'Karşı Vuruş Savunması' }, description: { ru: 'Защититесь с угрозой в ответ.', en: 'Defend while creating counter-threat.', tr: 'Karşı tehdit yaratarak savun.' }, category: 'defense', difficulty: 'hard', fen: '6k1/5ppp/8/8/8/2Q5/5PPP/6K1 w - - 0 1', solution: 'c3c8', hint: hint.defense, reward: 73 },
  { id: 37, title: { ru: 'Король в укрытие', en: 'King Shelter', tr: 'Şah Sığınağı' }, description: { ru: 'Король должен найти безопасное поле.', en: 'King must find safe square.', tr: 'Şah güvenli kare bulmalı.' }, category: 'defense', difficulty: 'medium', fen: '8/5pk1/8/8/8/8/5PPP/3Q2K1 w - - 0 1', solution: 'g1h1', hint: hint.defense, reward: 46 },
  { id: 38, title: { ru: 'Защита от связки', en: 'Defend Against Pin', tr: 'Açmaza Karşı Savun' }, description: { ru: 'Разорвите неприятную связку.', en: 'Break the dangerous pin.', tr: 'Tehlikeli açmazı kır.' }, category: 'defense', difficulty: 'expert', fen: 'r3k2r/ppp2ppp/8/8/3P4/2N2N2/PP3PPP/R1BQK2R w KQkq - 0 1', solution: 'f3e5', hint: hint.defense, reward: 108 },

  { id: 39, title: { ru: 'Активный король', en: 'Active King', tr: 'Aktif Şah' }, description: { ru: 'Король идёт в центр.', en: 'King steps to center.', tr: 'Şah merkeze gider.' }, category: 'endgame', difficulty: 'easy', fen: '8/5pk1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'g1f1', hint: hint.defense, reward: 31 },
  { id: 40, title: { ru: 'Оппозиция', en: 'Opposition', tr: 'Muhalefet' }, description: { ru: 'Возьмите оппозицию королём.', en: 'Take king opposition.', tr: 'Şahla muhalefeti al.' }, category: 'endgame', difficulty: 'medium', fen: '8/8/4k3/8/4K3/8/8/8 w - - 0 1', solution: 'e4d4', hint: hint.defense, reward: 45 },
  { id: 41, title: { ru: 'Ладья позади пешки', en: 'Rook Behind Pawn', tr: 'Piyon Arkasında Kale' }, description: { ru: 'Классический принцип эндшпиля.', en: 'Classic endgame principle.', tr: 'Klasik oyunsonu ilkesi.' }, category: 'endgame', difficulty: 'medium', fen: '6k1/5ppp/8/3P4/8/8/5PPP/3R2K1 w - - 0 1', solution: 'd1d4', hint: hint.defense, reward: 52 },
  { id: 42, title: { ru: 'Прорыв королём', en: 'King Breakthrough', tr: 'Şahla Geçiş' }, description: { ru: 'Точный ход королём в пешечном эндшпиле.', en: 'Precise king move in pawn endgame.', tr: 'Piyon oyunsonunda kesin şah hamlesi.' }, category: 'endgame', difficulty: 'hard', fen: '8/8/8/3k4/3P4/8/4K3/8 w - - 0 1', solution: 'e2e3', hint: hint.defense, reward: 70 },
  { id: 43, title: { ru: 'Ладейная активность', en: 'Rook Activity', tr: 'Kale Aktivitesi' }, description: { ru: 'Ладья должна стать активной.', en: 'Rook must become active.', tr: 'Kale aktifleşmeli.' }, category: 'endgame', difficulty: 'medium', fen: '6k1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1', solution: 'f1d1', hint: hint.defense, reward: 50 },
  { id: 44, title: { ru: 'Точность в ладейном', en: 'Rook Endgame Precision', tr: 'Kale Oyunsonu Hassasiyeti' }, description: { ru: 'Единственный путь к ничьей/выигрышу.', en: 'Only route to hold or win.', tr: 'Beraberlik/kazanç için tek yol.' }, category: 'endgame', difficulty: 'expert', fen: '8/5pk1/8/8/8/1R6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.defense, reward: 101 },

  { id: 45, title: { ru: 'Простой проход', en: 'Simple Promotion', tr: 'Basit Terfi' }, description: { ru: 'Проведите пешку в ферзи.', en: 'Promote the pawn.', tr: 'Piyonu terfi ettir.' }, category: 'promotion', difficulty: 'medium', fen: '8/2P3k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'c7c8', hint: hint.tactic, reward: 58 },
  { id: 46, title: { ru: 'Терфи с шахом', en: 'Promotion with Check', tr: 'Şahla Terfi' }, description: { ru: 'Превращение с темпом.', en: 'Promote with tempo.', tr: 'Tempoyla terfi et.' }, category: 'promotion', difficulty: 'expert', fen: '8/1P4k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'b7b8', hint: hint.tactic, reward: 120 },
  { id: 47, title: { ru: 'Пешка решает партию', en: 'Pawn Decides Game', tr: 'Piyon Oyunu Belirler' }, description: { ru: 'Рассчитайте гонку пешек.', en: 'Calculate pawn race.', tr: 'Piyon yarışını hesapla.' }, category: 'promotion', difficulty: 'hard', fen: '8/3P2k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'd7d8', hint: hint.tactic, reward: 78 },
  { id: 48, title: { ru: 'Поддержанная проходная', en: 'Supported Passed Pawn', tr: 'Destekli Geçer Piyon' }, description: { ru: 'Сначала король, потом терфи.', en: 'King support before promotion.', tr: 'Terfi öncesi şah desteği.' }, category: 'promotion', difficulty: 'medium', fen: '8/4P1k1/8/8/8/8/4KPPP/8 w - - 0 1', solution: 'e7e8', hint: hint.tactic, reward: 55 },
  { id: 49, title: { ru: 'Ладья против пешки', en: 'Rook vs Pawn Promotion', tr: 'Kale-Piyon Terfi' }, description: { ru: 'Найдите точный момент превращения.', en: 'Find exact promotion moment.', tr: 'Kesin terfi anını bul.' }, category: 'promotion', difficulty: 'expert', fen: '8/6P1/6k1/8/8/8/6K1/8 w - - 0 1', solution: 'g7g8', hint: hint.tactic, reward: 126 },

  { id: 50, title: { ru: 'Центральный удар', en: 'Central Blow', tr: 'Merkez Darbesi' }, description: { ru: 'Тактический пробой центра.', en: 'Break through the center.', tr: 'Merkezi yar.' }, category: 'tactical', difficulty: 'medium', fen: 'r1b1k2r/ppp2ppp/2n1pn2/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w kq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 55 },
  { id: 51, title: { ru: 'Промежуточный шах', en: 'Intermediate Check', tr: 'Ara Şah' }, description: { ru: 'Найдите междуход с шахом.', en: 'Find an in-between check.', tr: 'Ara şah hamlesini bul.' }, category: 'tactical', difficulty: 'hard', fen: 'r1bqk2r/pppp1ppp/2n2n2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'f3e5', hint: hint.tactic, reward: 84 },
  { id: 52, title: { ru: 'Удаление защитника', en: 'Remove Defender', tr: 'Savunucuyu Kaldır' }, description: { ru: 'Уберите ключевую фигуру.', en: 'Eliminate key defender.', tr: 'Kilit savunucuyu kaldır.' }, category: 'tactical', difficulty: 'expert', fen: 'r2q1rk1/ppp2ppp/2n5/8/3P4/2N2N2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 112 },
  { id: 53, title: { ru: 'Тактика на диагонали', en: 'Diagonal Tactic', tr: 'Çapraz Taktik' }, description: { ru: 'Диагональ решает исход.', en: 'Diagonal decides the outcome.', tr: 'Çapraz sonucu belirler.' }, category: 'tactical', difficulty: 'hard', fen: 'r1bq1rk1/ppp2ppp/2n5/3n4/3P4/2N2N2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'c2h7', hint: hint.tactic, reward: 88 },
  { id: 54, title: { ru: 'Жертва качества', en: 'Exchange Sacrifice', tr: 'Kalite Fedası' }, description: { ru: 'Пожертвуйте ладью ради атаки.', en: 'Sac exchange for initiative.', tr: 'İnisiyatif için kalite feda et.' }, category: 'tactical', difficulty: 'expert', fen: 'r1bqk2r/ppp2ppp/2n1pn2/8/3P4/2N1PN2/PPQ2PPP/R1B1R1K1 w kq - 0 1', solution: 'e1e8', hint: hint.tactic, reward: 118 },
  { id: 55, title: { ru: 'Точный темп', en: 'Precise Tempo', tr: 'Kesin Tempo' }, description: { ru: 'Один темп меняет оценку.', en: 'One tempo changes evaluation.', tr: 'Bir tempo değerlendirmeyi değiştirir.' }, category: 'tactical', difficulty: 'medium', fen: 'rnbqk2r/pppp1ppp/4pn2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'c3b5', hint: hint.tactic, reward: 60 },
  { id: 56, title: { ru: 'Комбинация на короля', en: 'King-side Combination', tr: 'Şah Kanadı Kombinasyonu' }, description: { ru: 'Серия форсирующих ходов.', en: 'Sequence of forcing moves.', tr: 'Zorlayıcı hamle serisi.' }, category: 'tactical', difficulty: 'hard', fen: 'r1bq1rk1/ppp2ppp/2n5/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'f3g5', hint: hint.tactic, reward: 74 },

  { id: 57, title: { ru: 'Охота на ферзя', en: 'Queen Hunt', tr: 'Vezir Avı' }, description: { ru: 'Выиграйте ферзя тактикой.', en: 'Win the queen tactically.', tr: 'Taktikle veziri kazan.' }, category: 'winQueen', difficulty: 'hard', fen: 'r1bq1rk1/pppp1ppp/2n5/4p3/3nP3/5N2/PPP2PPP/RNBQ1RK1 w - - 0 1', solution: 'f3d4', hint: hint.tactic, reward: 86 },
  { id: 58, title: { ru: 'Ферзь в ловушке', en: 'Queen Trap', tr: 'Vezir Tuzağı' }, description: { ru: 'Ограничьте поля отхода ферзя.', en: 'Limit queen escape squares.', tr: 'Vezirin kaçış karelerini kısıtla.' }, category: 'winQueen', difficulty: 'expert', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/8/PPP2PPP/RNBQK2R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 122 },
  { id: 59, title: { ru: 'Связка выигрывает ферзя', en: 'Pin Wins Queen', tr: 'Açmaz Vezir Kazandırır' }, description: { ru: 'Используйте связку против ферзя.', en: 'Use pin to win queen.', tr: 'Vezir kazanmak için açmaz kullan.' }, category: 'winQueen', difficulty: 'hard', fen: 'r1b1k2r/ppp2ppp/2n1pn2/3q4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w kq - 0 1', solution: 'c2h7', hint: hint.tactic, reward: 90 },
  { id: 60, title: { ru: 'Манёвр против ферзя', en: 'Maneuver Against Queen', tr: 'Vezire Karşı Manevra' }, description: { ru: 'Конь отрезает ферзя.', en: 'Knight cuts off queen.', tr: 'At veziri keser.' }, category: 'winQueen', difficulty: 'medium', fen: 'r2q1rk1/ppp2ppp/2n5/3n4/3P4/2N2N2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3b5', hint: hint.tactic, reward: 57 },
  { id: 61, title: { ru: 'Выигрыш ферзя в эндшпиле', en: 'Endgame Queen Win', tr: 'Oyunsonunda Vezir Kazancı' }, description: { ru: 'Точный ход ладьёй ловит ферзя.', en: 'Precise rook move traps queen.', tr: 'Kesin kale hamlesi veziri hapseder.' }, category: 'winQueen', difficulty: 'expert', fen: '6k1/8/8/8/8/2q5/5PPP/3R2K1 w - - 0 1', solution: 'd1c1', hint: hint.tactic, reward: 114 }
];
