const tr = {
  categories: {
    mate1: { ru: 'Мат в 1 ход', en: 'Mate in 1', tr: '1 Hamlede Mat' },
    mate2: { ru: 'Мат в 2 хода', en: 'Mate in 2', tr: '2 Hamlede Mat' },
    fork: { ru: 'Вилка', en: 'Fork', tr: 'Çatal' },
    pin: { ru: 'Связка', en: 'Pin', tr: 'Açmaz' },
    discovered: { ru: 'Вскрытое нападение', en: 'Discovered Attack', tr: 'Açık Saldırı' },
    defense: { ru: 'Защита', en: 'Defense', tr: 'Savunma' },
    endgame: { ru: 'Эндшпиль', en: 'Endgame', tr: 'Oyunsonu' },
    promotion: { ru: 'Превращение пешки', en: 'Promotion', tr: 'Terfi' },
    tactical: { ru: 'Тактика', en: 'Tactics', tr: 'Taktik' },
    winQueen: { ru: 'Выигрыш ферзя', en: 'Win the Queen', tr: 'Veziri Kazan' }
  },
  difficulty: {
    all: { ru: 'Все', en: 'All', tr: 'Tümü' },
    easy: { ru: 'Легко', en: 'Easy', tr: 'Kolay' },
    medium: { ru: 'Средне', en: 'Medium', tr: 'Orta' },
    hard: { ru: 'Сложно', en: 'Hard', tr: 'Zor' },
    expert: { ru: 'Эксперт', en: 'Expert', tr: 'Uzman' }
  }
};

export function getPuzzleLabel(type, lang='ru') { return tr.categories[type]?.[lang] || type; }
export function getDifficultyLabel(level, lang='ru') { return tr.difficulty[level]?.[lang] || level; }

const hint = {
  mate: { ru: 'Ищите форсирующий шах.', en: 'Look for a forcing check.', tr: 'Zorlayıcı şahı ara.' },
  tactic: { ru: 'Считайте взятия до конца.', en: 'Calculate captures to the end.', tr: 'Alışları sonuna kadar hesapla.' },
  defense: { ru: 'Устраните главную угрозу.', en: 'Neutralize the main threat.', tr: 'Ana tehdidi etkisizleştir.' }
};

export const puzzles = [
  { id: 1, title: { ru: 'Мат диагональю', en: 'Diagonal Mate', tr: 'Çapraz Mat' }, description: { ru: 'Мат в 1 ход.', en: 'Mate in 1.', tr: '1 hamlede mat.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/5PPP/6KQ w - - 0 1', solution: 'h1d8', hint: hint.mate, reward: 35 },
  { id: 2, title: { ru: 'Мат ладьёй', en: 'Rook Mate', tr: 'Kale Matı' }, description: { ru: 'Мат по восьмой.', en: 'Mate on 8th rank.', tr: '8. yatayda mat.' }, category: 'mate1', difficulty: 'easy', fen: '7k/8/6K1/8/8/8/8/R7 w - - 0 1', solution: 'a1a8', hint: hint.mate, reward: 34 },
  { id: 3, title: { ru: 'Мат ферзём', en: 'Queen Mate', tr: 'Vezir Matı' }, description: { ru: 'Точный матующий ход.', en: 'Exact mating move.', tr: 'Kesin mat hamlesi.' }, category: 'mate1', difficulty: 'easy', fen: '8/5pk1/8/8/8/3Q4/5PPP/6K1 w - - 0 1', solution: 'd3d8', hint: hint.mate, reward: 30 },
  { id: 4, title: { ru: 'Закрытый король', en: 'Boxed King', tr: 'Kapalı Şah' }, description: { ru: 'Используйте слабую последнюю линию.', en: 'Exploit weak back rank.', tr: 'Zayıf arka hattı kullan.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/2Q5/5PPP/6K1 w - - 0 1', solution: 'c3c8', hint: hint.mate, reward: 37 },
  { id: 5, title: { ru: 'Тихий ключ', en: 'Quiet Key', tr: 'Sessiz Anahtar' }, description: { ru: 'Начните мат в 2 хода.', en: 'Start mate in 2.', tr: '2 hamlede matı başlat.' }, category: 'mate2', difficulty: 'medium', fen: '8/5pk1/5np1/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 52 },
  { id: 6, title: { ru: 'Отклонение', en: 'Deflection Mate', tr: 'Saptırma Matı' }, description: { ru: 'Уберите защитника.', en: 'Deflect the defender.', tr: 'Savunucuyu saptır.' }, category: 'mate2', difficulty: 'hard', fen: '5rk1/5ppp/8/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 76 },
  { id: 7, title: { ru: 'Конь в центре', en: 'Knight in Center', tr: 'Merkezde At' }, description: { ru: 'Сделайте вилку.', en: 'Play a fork.', tr: 'Çatal yap.' }, category: 'fork', difficulty: 'easy', fen: '4k3/8/8/3q4/8/4N3/8/4K3 w - - 0 1', solution: 'e3d5', hint: hint.tactic, reward: 38 },
  { id: 8, title: { ru: 'Вилка в дебюте', en: 'Opening Fork', tr: 'Açılış Çatalı' }, description: { ru: 'Выиграйте темп и материал.', en: 'Win tempo and material.', tr: 'Tempo ve taş kazan.' }, category: 'fork', difficulty: 'easy', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/5N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 39 },
  { id: 9, title: { ru: 'Сдвоенная цель', en: 'Double Target', tr: 'Çifte Hedef' }, description: { ru: 'Конь бьёт две фигуры.', en: 'Knight hits two pieces.', tr: 'At iki taşı vurur.' }, category: 'fork', difficulty: 'medium', fen: 'r2q1rk1/ppp2ppp/2n5/3n4/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 54 },
  { id: 10, title: { ru: 'Вилка с выигрышем ладьи', en: 'Fork wins rook', tr: 'Çatal kale kazanır' }, description: { ru: 'Заберите тяжёлую фигуру.', en: 'Win a heavy piece.', tr: 'Ağır taş kazan.' }, category: 'fork', difficulty: 'hard', fen: 'r1bq1rk1/ppp2ppp/2n5/3n4/3P4/2N2N2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 72 },
  { id: 11, title: { ru: 'Связка по линии', en: 'File Pin', tr: 'Dikey Açmaz' }, description: { ru: 'Свяжите фигуру и давите.', en: 'Pin and press.', tr: 'Açmaz yap ve baskı kur.' }, category: 'pin', difficulty: 'medium', fen: '2r3k1/5ppp/3q4/8/3Q4/8/5PPP/6K1 w - - 0 1', solution: 'd4d6', hint: hint.tactic, reward: 50 },
  { id: 12, title: { ru: 'Дальняя связка', en: 'Long Pin', tr: 'Uzun Açmaz' }, description: { ru: 'Связка решает позицию.', en: 'Pin decides position.', tr: 'Açmaz pozisyonu çözer.' }, category: 'pin', difficulty: 'hard', fen: '2r3k1/5ppp/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.tactic, reward: 73 },
  { id: 13, title: { ru: 'Диагональная связка', en: 'Diagonal Pin', tr: 'Çapraz Açmaz' }, description: { ru: 'Сковать королевского защитника.', en: 'Pin king defender.', tr: 'Şah savunucusunu bağla.' }, category: 'pin', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.tactic, reward: 79 },
  { id: 14, title: { ru: 'Вскрытый нажим', en: 'Discovered Pressure', tr: 'Açık Baskı' }, description: { ru: 'Откройте атаку.', en: 'Open the attack.', tr: 'Saldırıyı aç.' }, category: 'discovered', difficulty: 'medium', fen: 'r3k2r/ppp2ppp/2n5/3qp3/3P4/2P2N2/PP3PPP/R1BQ1RK1 w kq - 0 1', solution: 'd4e5', hint: hint.tactic, reward: 56 },
  { id: 15, title: { ru: 'Скрытый выстрел', en: 'Hidden Shot', tr: 'Gizli Vuruş' }, description: { ru: 'Вскрытое нападение на ферзя.', en: 'Discovered attack on queen.', tr: 'Vezire açık saldırı.' }, category: 'discovered', difficulty: 'hard', fen: 'r1b1k2r/ppp2ppp/2n1pn2/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w kq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 80 },
  { id: 16, title: { ru: 'Вскрытый шах', en: 'Discovered Check', tr: 'Açık Şah' }, description: { ru: 'Откройте линию шаха.', en: 'Open line for check.', tr: 'Şah hattını aç.' }, category: 'discovered', difficulty: 'expert', fen: 'r1bqk2r/pppp1ppp/4pn2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 104 },
  { id: 17, title: { ru: 'Единственный щит', en: 'Only Shield', tr: 'Tek Kalkan' }, description: { ru: 'Защита от мата.', en: 'Defend against mate.', tr: 'Matı savun.' }, category: 'defense', difficulty: 'easy', fen: '4k3/8/8/8/8/8/5q2/4K2R w - - 0 1', solution: 'e1f2', hint: hint.defense, reward: 33 },
  { id: 18, title: { ru: 'Точный размен', en: 'Precise Trade', tr: 'Kesin Değişim' }, description: { ru: 'Упростите и спаситесь.', en: 'Simplify and survive.', tr: 'Sadeleştir ve kurtul.' }, category: 'defense', difficulty: 'medium', fen: '4r1k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1', solution: 'd1d8', hint: hint.defense, reward: 48 },
  { id: 19, title: { ru: 'Защита с контригрой', en: 'Defense with Counterplay', tr: 'Karşı Oyunlu Savunma' }, description: { ru: 'Защититесь и атакуйте.', en: 'Defend and threaten.', tr: 'Savun ve tehdit et.' }, category: 'defense', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/2Q5/5PPP/6K1 w - - 0 1', solution: 'c3c8', hint: hint.defense, reward: 71 },
  { id: 20, title: { ru: 'Ладейный актив', en: 'Rook Activity', tr: 'Kale Aktivitesi' }, description: { ru: 'Активизируйте ладью.', en: 'Activate rook.', tr: 'Kaleyi aktifleştir.' }, category: 'endgame', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1', solution: 'f1d1', hint: hint.defense, reward: 32 },
  { id: 21, title: { ru: 'Пешечный план', en: 'Pawn Plan', tr: 'Piyon Planı' }, description: { ru: 'Решающий эндшпильный толчок.', en: 'Decisive endgame push.', tr: 'Belirleyici oyunsonu sürüşü.' }, category: 'endgame', difficulty: 'medium', fen: '8/5pk1/8/8/8/8/5PPP/2Q3K1 w - - 0 1', solution: 'c1c8', hint: hint.tactic, reward: 45 },
  { id: 22, title: { ru: 'Точный король', en: 'Precise King', tr: 'Kesin Şah' }, description: { ru: 'Ход королём спасает позицию.', en: 'King move saves game.', tr: 'Şah hamlesi oyunu kurtarır.' }, category: 'endgame', difficulty: 'hard', fen: '8/5pk1/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.defense, reward: 74 },
  { id: 23, title: { ru: 'Прорыв пешки', en: 'Pawn Break', tr: 'Piyon Kırışı' }, description: { ru: 'Путь к превращению.', en: 'Path to promotion.', tr: 'Terfiye giden yol.' }, category: 'promotion', difficulty: 'medium', fen: '6k1/5ppp/8/8/8/8/4QPPP/6K1 w - - 0 1', solution: 'e2e8', hint: hint.tactic, reward: 58 },
  { id: 24, title: { ru: 'Новая ферзь', en: 'New Queen', tr: 'Yeni Vezir' }, description: { ru: 'Пешка должна превратиться.', en: 'Pawn must promote.', tr: 'Piyon terfi etmeli.' }, category: 'promotion', difficulty: 'expert', fen: '8/2P3k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'c7c8', hint: hint.mate, reward: 112 },
  { id: 25, title: { ru: 'Превращение с шахом', en: 'Promotion with Check', tr: 'Şahla Terfi' }, description: { ru: 'Превратитесь с темпом.', en: 'Promote with tempo.', tr: 'Tempoyla terfi et.' }, category: 'promotion', difficulty: 'expert', fen: '8/1P4k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'b7b8', hint: hint.tactic, reward: 125 },
  { id: 26, title: { ru: 'Центральный удар', en: 'Central Blow', tr: 'Merkez Darbesi' }, description: { ru: 'Тактический пробой центра.', en: 'Break through center.', tr: 'Merkezi yar.' }, category: 'tactical', difficulty: 'medium', fen: 'r1b1k2r/ppp2ppp/2n1pn2/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w kq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 55 },
  { id: 27, title: { ru: 'Междуход', en: 'Zwischenzug', tr: 'Ara Hamle' }, description: { ru: 'Найдите сильный промежуточный ход.', en: 'Find strong in-between move.', tr: 'Güçlü ara hamleyi bul.' }, category: 'tactical', difficulty: 'hard', fen: 'r1bqk2r/pppp1ppp/2n2n2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 78 },
  { id: 28, title: { ru: 'Удаление защитника', en: 'Remove Defender', tr: 'Savunucuyu Kaldır' }, description: { ru: 'Снимите ключевую защиту.', en: 'Remove key defender.', tr: 'Kilit savunucuyu kaldır.' }, category: 'tactical', difficulty: 'expert', fen: 'r2q1rk1/ppp2ppp/2n5/8/3P4/2N2N2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 106 },
  { id: 29, title: { ru: 'Охота на ферзя', en: 'Queen Hunt', tr: 'Vezir Avı' }, description: { ru: 'Выиграйте ферзя.', en: 'Win the queen.', tr: 'Veziri kazan.' }, category: 'winQueen', difficulty: 'hard', fen: 'r1bq1rk1/pppp1ppp/2n5/4p3/3nP3/5N2/PPP2PPP/RNBQ1RK1 w - - 0 1', solution: 'f3d4', hint: hint.tactic, reward: 84 },
  { id: 30, title: { ru: 'Ловушка ферзя', en: 'Queen Trap', tr: 'Vezir Tuzağı' }, description: { ru: 'Загоните ферзя в сеть.', en: 'Trap queen in net.', tr: 'Veziri ağa yakala.' }, category: 'winQueen', difficulty: 'expert', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/8/PPP2PPP/RNBQK2R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 120 },
  { id: 31, title: { ru: 'Выигрыш ферзя связкой', en: 'Pin wins queen', tr: 'Açmaz vezir kazanır' }, description: { ru: 'Связка лишает ферзя защиты.', en: 'Pin removes queen defense.', tr: 'Açmaz vezir savunmasını kaldırır.' }, category: 'winQueen', difficulty: 'hard', fen: 'r1b1k2r/ppp2ppp/2n1pn2/3q4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w kq - 0 1', solution: 'c2h7', hint: hint.tactic, reward: 89 },
  { id: 32, title: { ru: 'Мат по первой', en: 'First Rank Mate', tr: 'Birinci Hat Matı' }, description: { ru: 'Немедленный мат.', en: 'Immediate mate.', tr: 'Anında mat.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1', solution: 'd1d8', hint: hint.mate, reward: 36 },
  { id: 33, title: { ru: 'Мат дальним ходом', en: 'Long Mate', tr: 'Uzak Mat' }, description: { ru: 'Ферзь с дальнего рубежа.', en: 'Queen from distance.', tr: 'Uzak mesafeden vezir.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5pp1/7p/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.mate, reward: 34 },
  { id: 34, title: { ru: 'Мат через линию', en: 'Line Mate', tr: 'Hat Matı' }, description: { ru: 'Откройте линию мата.', en: 'Open mating line.', tr: 'Mat hattını aç.' }, category: 'mate1', difficulty: 'easy', fen: '8/5pk1/6p1/8/8/5Q2/5PPP/6K1 w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 31 },
  { id: 35, title: { ru: 'Мат с переводом', en: 'Transfer Mate', tr: 'Geçişli Mat' }, description: { ru: 'Поставьте ферзя на решающую клетку.', en: 'Transfer queen to key square.', tr: 'Veziri kilit kareye taşı.' }, category: 'mate2', difficulty: 'medium', fen: '4r1k1/5ppp/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.mate, reward: 50 },
  { id: 36, title: { ru: 'Точная подготовка', en: 'Exact Setup', tr: 'Kesin Hazırlık' }, description: { ru: 'Подготовьте второй решающий ход.', en: 'Prepare decisive second move.', tr: 'Belirleyici ikinci hamleyi hazırla.' }, category: 'mate2', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/8/5PPP/2Q3K1 w - - 0 1', solution: 'c1c8', hint: hint.mate, reward: 77 },
  { id: 37, title: { ru: 'Вилка из засады', en: 'Ambush Fork', tr: 'Pusu Çatalı' }, description: { ru: 'Неочевидный ход коня.', en: 'Hidden knight jump.', tr: 'Gizli at sıçrayışı.' }, category: 'fork', difficulty: 'medium', fen: 'r2q1rk1/ppp2ppp/2n5/8/3P4/2N2N2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 51 },
  { id: 38, title: { ru: 'Форк на выходе', en: 'Exit Fork', tr: 'Çıkış Çatalı' }, description: { ru: 'Тактический ресурс в защите.', en: 'Tactical resource in defense.', tr: 'Savunmada taktik kaynak.' }, category: 'fork', difficulty: 'hard', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 70 },
  { id: 39, title: { ru: 'Связка и давление', en: 'Pin and Pressure', tr: 'Açmaz ve Baskı' }, description: { ru: 'Связка усиливает атаку.', en: 'Pin boosts attack.', tr: 'Açmaz saldırıyı güçlendirir.' }, category: 'pin', difficulty: 'medium', fen: '2r3k1/5ppp/8/8/3Q4/8/5PPP/6K1 w - - 0 1', solution: 'd4d6', hint: hint.tactic, reward: 57 },
  { id: 40, title: { ru: 'Жёсткая связка', en: 'Hard Pin', tr: 'Sert Açmaz' }, description: { ru: 'Закрепите фигуру окончательно.', en: 'Freeze the pinned piece.', tr: 'Açmazdaki taşı dondur.' }, category: 'pin', difficulty: 'expert', fen: '2r3k1/5ppp/3q4/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.tactic, reward: 102 },
  { id: 41, title: { ru: 'Вскрытие центра', en: 'Open the Center', tr: 'Merkezi Aç' }, description: { ru: 'Вскрытый удар по королю.', en: 'Discovered hit on king.', tr: 'Şaha açık vuruş.' }, category: 'discovered', difficulty: 'medium', fen: 'r1bq1rk1/ppp2ppp/2n5/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 47 },
  { id: 42, title: { ru: 'Линия вскрыта', en: 'Line Opened', tr: 'Hat Açıldı' }, description: { ru: 'Откройте фигурам путь.', en: 'Open path for pieces.', tr: 'Taşlara yol aç.' }, category: 'discovered', difficulty: 'hard', fen: 'rnbqk2r/pppp1ppp/4pn2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 81 },
  { id: 43, title: { ru: 'Шаг назад', en: 'Step Back', tr: 'Geri Adım' }, description: { ru: 'Защитный манёвр.', en: 'Defensive maneuver.', tr: 'Savunma manevrası.' }, category: 'defense', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/5PPP/3Q3K w - - 0 1', solution: 'd1d8', hint: hint.defense, reward: 40 },
  { id: 44, title: { ru: 'Спасение позиции', en: 'Position Save', tr: 'Pozisyonu Kurtar' }, description: { ru: 'Найдите ресурс спасения.', en: 'Find saving resource.', tr: 'Kurtarıcı kaynağı bul.' }, category: 'defense', difficulty: 'hard', fen: '6k1/5ppp/8/8/8/8/4QPPP/7K w - - 0 1', solution: 'e2e8', hint: hint.defense, reward: 83 },
  { id: 45, title: { ru: 'Король активен', en: 'Active King', tr: 'Aktif Şah' }, description: { ru: 'Эндшпиль требует активности.', en: 'Endgame needs activity.', tr: 'Oyunsonunda aktivite gerek.' }, category: 'endgame', difficulty: 'medium', fen: '8/5pk1/8/8/8/2Q5/5PPP/6K1 w - - 0 1', solution: 'c3c8', hint: hint.defense, reward: 59 },
  { id: 46, title: { ru: 'Ладейный мост', en: 'Rook Bridge', tr: 'Kale Köprüsü' }, description: { ru: 'Классический приём в эндшпиле.', en: 'Classic endgame technique.', tr: 'Klasik oyunsonu tekniği.' }, category: 'endgame', difficulty: 'expert', fen: '6k1/5ppp/8/8/8/8/5PPP/1Q4K1 w - - 0 1', solution: 'b1b8', hint: hint.defense, reward: 108 },
  { id: 47, title: { ru: 'Точный расчёт превращения', en: 'Promotion Calculation', tr: 'Terfi Hesabı' }, description: { ru: 'Найдите верный момент превращения.', en: 'Find right promotion moment.', tr: 'Doğru terfi anını bul.' }, category: 'promotion', difficulty: 'hard', fen: '6k1/5ppp/8/8/8/8/4QPPP/7K w - - 0 1', solution: 'e2e8', hint: hint.tactic, reward: 74 },
  { id: 48, title: { ru: 'Пешка решает', en: 'Pawn Decides', tr: 'Piyon Karar Verir' }, description: { ru: 'Продвиньте проходную до конца.', en: 'Push passer to finish.', tr: 'Geçer piyonu sona götür.' }, category: 'promotion', difficulty: 'expert', fen: '8/3P2k1/8/8/8/8/5PPP/6K1 w - - 0 1', solution: 'd7d8', hint: hint.tactic, reward: 130 },
  { id: 49, title: { ru: 'Тактический штурм', en: 'Tactical Storm', tr: 'Taktik Fırtına' }, description: { ru: 'Серия форсирующих ходов начинается сейчас.', en: 'Forcing sequence starts now.', tr: 'Zorlayıcı seri şimdi başlar.' }, category: 'tactical', difficulty: 'medium', fen: 'r1bq1rk1/ppp2ppp/2n5/8/3P4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 60 },
  { id: 50, title: { ru: 'Тактический удар по центру', en: 'Center Tactic', tr: 'Merkez Taktiği' }, description: { ru: 'Ударьте в перегруженную фигуру.', en: 'Hit overloaded piece.', tr: 'Aşırı yüklü taşa vur.' }, category: 'tactical', difficulty: 'hard', fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/3NP3/8/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 86 },
  { id: 51, title: { ru: 'Выигрыш ферзя манёвром', en: 'Queen Win by Maneuver', tr: 'Manevra ile Vezir Kazancı' }, description: { ru: 'Подготовьте ловушку для ферзя.', en: 'Set a trap for queen.', tr: 'Vezir için tuzak kur.' }, category: 'winQueen', difficulty: 'hard', fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: 'd4c6', hint: hint.tactic, reward: 90 },
  { id: 52, title: { ru: 'Ферзь без полей', en: 'Queen Out of Squares', tr: 'Vezirin Kaçışı Yok' }, description: { ru: 'Ограничьте ферзя и выиграйте.', en: 'Limit queen and win it.', tr: 'Veziri kısıtla ve kazan.' }, category: 'winQueen', difficulty: 'expert', fen: 'r2q1rk1/ppp2ppp/2n5/3n4/3P4/2N2N2/PP3PPP/R1BQ1RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 118 },
  { id: 53, title: { ru: 'Ферзевый захват', en: 'Queen Capture Plan', tr: 'Vezir Yakalama Planı' }, description: { ru: 'Рассчитайте выигрыш ферзя.', en: 'Calculate queen win.', tr: 'Vezir kazancını hesapla.' }, category: 'winQueen', difficulty: 'expert', fen: 'r1b1k2r/ppp2ppp/2n1pn2/3q4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w kq - 0 1', solution: 'c2h7', hint: hint.tactic, reward: 121 },
  { id: 54, title: { ru: 'Матовое поле', en: 'Mating Square', tr: 'Mat Karesi' }, description: { ru: 'Прямой мат в 1.', en: 'Direct mate in 1.', tr: 'Doğrudan 1 hamlede mat.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/5Q2/5PPP/7K w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 33 },
  { id: 55, title: { ru: 'Мат по колонке', en: 'File Finish', tr: 'Dikey Bitiş' }, description: { ru: 'Линейный завершающий ход.', en: 'Linear finishing move.', tr: 'Doğrusal bitiriş hamlesi.' }, category: 'mate1', difficulty: 'easy', fen: '6k1/5ppp/8/8/8/8/4QPPP/6K1 w - - 0 1', solution: 'e2e8', hint: hint.mate, reward: 32 },
  { id: 56, title: { ru: 'Двухходовка с жертвой', en: 'Two-move Sacrifice', tr: '2 Hamlede Fedalı Mat' }, description: { ru: 'Найдите жертву для мата в 2.', en: 'Find sacrifice for mate in 2.', tr: '2 hamlede mat için fedayı bul.' }, category: 'mate2', difficulty: 'expert', fen: '8/5pk1/8/8/8/5Q2/5PPP/7K w - - 0 1', solution: 'f3a8', hint: hint.mate, reward: 101 },
  { id: 57, title: { ru: 'Вилка в конце', en: 'Late Fork', tr: 'Geç Çatal' }, description: { ru: 'Последний тактический ресурс.', en: 'Last tactical resource.', tr: 'Son taktik kaynak.' }, category: 'fork', difficulty: 'medium', fen: 'r2q1rk1/ppp2ppp/2n5/3n4/3P4/2N2N2/PPQ2PPP/R1B2RK1 w - - 0 1', solution: 'c3d5', hint: hint.tactic, reward: 53 },
  { id: 58, title: { ru: 'Связка на спасение', en: 'Saving Pin', tr: 'Kurtarıcı Açmaz' }, description: { ru: 'Связка как защитный ресурс.', en: 'Pin as defensive resource.', tr: 'Savunma kaynağı olarak açmaz.' }, category: 'pin', difficulty: 'hard', fen: '4r1k1/5ppp/8/8/8/1Q6/5PPP/6K1 w - - 0 1', solution: 'b3b8', hint: hint.defense, reward: 70 },
  { id: 59, title: { ru: 'Вскрытая ловушка', en: 'Discovered Trap', tr: 'Açık Tuzak' }, description: { ru: 'Вскройте атаку и выиграйте материал.', en: 'Open attack and win material.', tr: 'Saldırıyı aç ve taş kazan.' }, category: 'discovered', difficulty: 'expert', fen: 'r1bqk2r/pppp1ppp/2n2n2/8/3P4/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: 'd4d5', hint: hint.tactic, reward: 103 },
  { id: 60, title: { ru: 'Финальная оборона', en: 'Final Defense', tr: 'Son Savunma' }, description: { ru: 'Спасите позицию точным ходом.', en: 'Save position with precise move.', tr: 'Kesin hamleyle pozisyonu kurtar.' }, category: 'defense', difficulty: 'expert', fen: '4r1k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1', solution: 'd1d8', hint: hint.defense, reward: 115 }
];
